### PR TITLE
uses .gz files if present, like nginx gzip_static module

### PR DESCRIPTION
**Pull request by AlexeyKhristov**

### CODE REVIEW

**Comment by dead-horse** [comment]
is this necessary? can we just leave it to let node handle the gzip?

**Comment by AlexeyKhristov** [comment]
@dead-horse I can find out 2 cases:
1. (my case) someone has already written build system (gulp/grunt/etc) and gzip files already created outside, not need use gzip inside node.js (increase CPU usage)
2. if you need use gzip compression, other then default, (for example max compression =9) - you can  externally create file

**Comment by dead-horse** [comment]
can we make this configuable? for compatibility.

**Comment by AlexeyKhristov** [comment]
like that? (see previous commit)

**Comment by AlexeyKhristov** [comment]
@dead-horse could you please publish (npm publish) new module version, if accept this request?

**Comment by dead-horse** [comment]
maybe we should filter `.gz` files, don't serve these files when `options. usePrecompiledGzip === true`.

**Comment by AlexeyKhristov** [comment]
@dead-horse you mean filter `.gz` files if `options. usePrecompiledGzip === false` (disabled read `.gz` from disk) ?

because if this option enabled we can't (as I saw it) filter `.gz` files - we should keep in memory 2 versions of file - compressed and not, depend on client accept encoding

**Comment by dead-horse** [comment]
if we have tow files:

- index.js
- index.js.gz

when people visit `/index.js.gz`, return 404, should this be more reasonable?

**Comment by AlexeyKhristov** [comment]
I think when people visit `/index.js.gz` we should return 200/304 with appropriate content type
My reasons - file exists and no need hide .gz files

@dead-horse if you think we should return 404 - I will change pull request

**Comment by dead-horse** [comment]
sounds reasonable

**Pull request merged**
