### PR TITLE
Fix broken mtime comparison

### PR DESCRIPTION
**Pull request by teohhanhui**
Date.prototype.toUTCString() does not have milliseconds

### CODE REVIEW

**Comment by fengmk2** [comment]
why remove ms compare?

**Comment by teohhanhui** [comment]
@fengmk2 No, this PR fixes the comparison by not using `Date.prototype.toUTCString()`.

**Comment by dead-horse** [comment]
LGTM

**Comment by dead-horse** [comment]
3.1.3

**Pull request merged**
